steps:
  - name: node:16.18.1
    entrypoint: npm
    args: ["install"]
  - name: node:16.18.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
  - name: node:16.18.1
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"